### ISSUE TITLE
I made a demo that can't run

### ISSUE THREAD

**Issue by apchenjun** [ikyriak/IdempotentAPI#14]
I created a web api project and run the console to report an error
```
        [HttpPost("Create")]
        [Idempotent()]
        public async Task<IActionResult> Create(WeatherForecastModel weatherForecastDto)
        {
            return new JsonResult(weatherForecastDto.Summary);
        }
       [Serializable]
       public class WeatherForecastModel
      {
        public string Summary { get; set; }
      }
```
I use postman to simulate the request
![image](https://user-images.githubusercontent.com/4964551/122256831-fe1a8580-cf01-11eb-99e5-045b99bd07e2.png)

![image](https://user-images.githubusercontent.com/4964551/122256372-96fcd100-cf01-11eb-9963-0379b441f82b.png)
Can the author make a demo that uses IdempotentAPI to simulate multiple repeated submissions that cannot be successful?

**Comment by ikyriak** [comment]
@apchenjun 
Thank you for reporting this issue. I have reproduced and fixed it.
You can download the updated version (v0.2.0-beta) of the library.
I have also uploaded a sample project (using .NET Core 3.1).
