### ISSUE TITLE
Not working in ASP .NET Core 5.0 - BinaryFormatter methods are obsolete

### ISSUE THREAD

**Issue by ikyriak** [ikyriak/IdempotentAPI#17]
BinaryFormatter serialization methods are [obsolete ](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete)in ASP .NET Core 5.0.  The BinaryFormatter is used in the `Utils.cs` class for Serializing and Deserializing the MemoryStream. 

The [recommended action](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete#recommended-action) is to stop using BinaryFormatter and consider using [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=net-5.0) or [XmlSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?view=net-5.0).

**Comment by fjsosa** [comment]
A **workaround** in the meantime: enable BinaryFormatterSerialization by adding this to the csproj:
<PropertyGroup>
   ...
  <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>

The idea of this library is excellent, waiting for new versions for net.core 5.0

**Comment by ikyriak** [comment]
The related improvement has been included in the [1.0.0 RC.01](https://github.com/ikyriak/IdempotentAPI/pull/30) release.

Please read the [README.md](https://github.com/ikyriak/IdempotentAPI#-quick-start) and [CHANGELOG.md](https://github.com/ikyriak/IdempotentAPI/blob/master/CHANGELOG.md) files because this release has breaking changes.

You can find the 1.0.0 RC.01 NuGet packages [here](https://www.nuget.org/packages?q=IdempotentAPI).

If you have any suggestions or comments please, do not hesitate to send them 😉
