### ISSUE TITLE
Get 409 status code when retry

### ISSUE THREAD

**Issue by khoavn** [ikyriak/IdempotentAPI#37]
I have 2 services, A and B and A calls B to create objects, and I use Polly to retry requests sent by A. The problem is when B crashed why processing request from A then Polly retries with same IdempotencyKey and it get 409 response instead re-run action method of B. Should we capture request/response only when request completed successfully? What should I do in this case?

**Comment by khoavn** [comment]
Hi @ikyriak,
Apologies for the delayed response. After upgrading I get this message:
`Unhandled exception. System.TypeLoadException: Method 'Remove' in type 'IdempotentAPI.Cache.FusionCache.IdempotencyFusionCache' from assembly 'IdempotentAPI.Cache.FusionCache, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`
when call `AddIdempotentAPIUsingFusionCache` method.

**Comment by ikyriak** [comment]
Hello @khoavn,

Oops! Sorry, I didn't publish the `1.0.2-prerelease-01` version of the `IdempotentAPI.Cache.FusionCache` library 😄.
You can find all the pre-release versions [here](https://www.nuget.org/packages?q=IdempotentAPI+ikyriakidis). Can you please try to update all the IdempotentAPI libraries that you use to `1.0.2-prerelease-01`?

**Comment by khoavn** [comment]
Thank you, it works now, but could we default `CacheOnlySuccessResponses` to `true`? I can't find cases where caching Controller crash useful.

**Comment by ikyriak** [comment]
Hello @khoavn,

We have set the default value of `CacheOnlySuccessResponses` to `true` in the [v2.0.0-RC.01](https://github.com/ikyriak/IdempotentAPI/blob/master/CHANGELOG.md#200-rc1---2022-10-02---breaking) release 🎆🎉. Thank you again for reporting this issue 🙏.
