### ISSUE TITLE
Specify the ExpireHour in Timestamp instead of int

### ISSUE THREAD

**Issue by vIceBerg** [ikyriak/IdempotentAPI#59]
Hi!

In our usecase scenario, the int for the ExpireHours is not flexible enough.

We would like to be able to specify 10 minutes. Or 30.  So forcing this parameter to be minimum 1 hour is not ideal.

Would it be possible to change the ExpireHours to ExpireDelay and from int to TimeSpan?

If I do a PR for it, would it be accepted?

**Comment by ikyriak** [comment]
Hello @vIceBerg 
Thank you for taking the time to report this.
If you have time, please prepare a PR.
Otherwise, I will implement it as soon as possible.

**Comment by vIceBerg** [comment]
Hi!

I'll try to do a PR today... Never done this, so maybe I'll need help with technical details

**Comment by vIceBerg** [comment]
Hi!

I try to push on a new branch and, of course, I get an unauthorized error. I need a little how-tos guide

**Comment by vIceBerg** [comment]
Ok I managed to do it! Pull Request is done!
