### ISSUE TITLE
Possibility to configure controllers via IdempotencyOptions

### ISSUE THREAD

**Issue by Jevvry** [ikyriak/IdempotentAPI#68]
There are projects that contain a large number of controllers. Because of this, important idempotency settings such as `ExpiresInMilliseconds`, `DistributedLockTimeoutMilli` are dispersed throughout the project. And this increases the likelihood of a configuration error.

It seems to me that it would be convenient to add the ability to configure controllers via DI registration of `IdempotencyOptions` and optionally use these settings in the `IdempotentAttribute`.

**Comment by ikyriak** [comment]
Hello @Jevvry,
Thank you for your time and implementation in configuring controllers via IdempotencyOptions.
This is an excellent idea. I will include some tests and improve the DependencyInjection extensions to easily register the IIdempotencyOptions.
