### ISSUE TITLE
For Minimal APIs, how to configure the idempotent options for a specific endpoint, not generally? (cache deadline, etc)

### ISSUE THREAD

**Issue by JonasLeetTheWay** [ikyriak/IdempotentAPI#73]
For Minimal APIs, how to configure the idempotent options for a specific endpoint, not generally? (cache deadline, etc)

In controllers, we can use attribute to configure, but how about Minimal APIs?

**Comment by ikyriak** [comment]
Hello @JonasLeetTheWay,

Thank you for opening this issue.

Currently, we can only set global idempotency options for MinimalAPIs. However, I have prepared a possible solution using an `IIdempotencyOptionsProvider` to provide the idempotency options based on our needs ([IdempotentAPI.MinimalAPI v3.1.0-issue-73-01](https://www.nuget.org/packages/IdempotentAPI.MinimalAPI/3.1.0-issue-73-01)).

Could this work in your case?

For example, we could return the `IIdempotencyOptions` based on the requested path.
```c#
public class IdempotencyOptionsProvider : IIdempotencyOptionsProvider
{
    public IIdempotencyOptions GetIdempotencyOptions(IHttpContextAccessor httpContextAccessor)
    {
        switch (httpContextAccessor?.HttpContext?.Request.Path)
        {
            case "/v6/TestingIdempotentAPI/test":
                return new IdempotencyOptions()
                {
                    ExpireHours = 1,
                };
        }

        return new IdempotencyOptions();
    }
}
```

We will need to register `IdempotencyOptionsProvider` in the `Program.cs`:
```
builder.Services.AddIdempotentMinimalAPI(new IdempotencyOptionsProvider());
```

**Comment by ikyriak** [comment]
This issue is resolved in the following stable version:
- [IdempotentAPI v2.5.0](https://www.nuget.org/packages/IdempotentAPI/2.5.0)
- [IdempotentAPI.MinimalAPI v3.1.0](https://www.nuget.org/packages/IdempotentAPI.MinimalAPI/3.1.0)
